version: "3.6"
volumes:
  data-volume: {}
services:
  db:
    image: "mysql"
    environment:
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ebdb
    ports: 
        - 3306:3306
    networks: 
      - tamjai-breakfast-order-web-app-network
    volumes: 
      - data-volume:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  web:
    # image: tamjai-breakfast-order-web-app
    ports: 
      - 8000:8000
    stdin_open: true
    depends_on: 
      - db
    networks: 
      - tamjai-breakfast-order-web-app-network
    build: ./
    # volumes: 
    # environment: 
    # ports: "3306:3306"
networks: 
  tamjai-breakfast-order-web-app-network:
    driver: bridge

