version: "3.6"
volumes:
  data-volume: {}
services:
  db:
    image: "mysql"
    environment:
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ebdb
    ports: 
        - 3307:3306
    networks: 
      - tamjai-breakfast-order-web-app-network
    # volumes: 
      # - ./init.sql:/drdocker-entrypoint-initdb.d/init.sql
    cap_add:
      - SYS_NICE
  web:
    # image: tamjai-breakfast-order-web-app
    ports: 
      - 8000:8000
    stdin_open: true
    depends_on: 
      - db
    networks: 
      - tamjai-breakfast-order-web-app-network
    build: ./
networks: 
  tamjai-breakfast-order-web-app-network:
    driver: bridge

