insert into items(english_item_name, traditional_chinese_item_name) values
	('Hot Milk Tea', '熱奶茶'),
    ('Hot Coffee', '熱咖啡'),
    ('Hot Yuan Yong', '熱鴛鴦'),
    ('Hot Lemon Tea', '熱檸茶'),
    ('Hot Lemon Tea', '熱檸水'),
    ('Hot Ovaltine', '熱阿華田'),
    ('Hot Horlicks', '熱可立克'),
    ('Hot Honey With Lemon','熱檸蜜'),
    ('Hot Honey With Watercress','熱菜蜜'),
    ('Cold Milk Tea','凍奶茶'),
    ('Cold Coffee','凍咖啡'),
    ('Cold Yuan Yang','凍鴛鴦'),
    ('Cold Lemon Tea','凍檸茶'),
    ('Cold Lemon Water','凍檸水'),
    ('Cold Ovaltine','凍阿華田'),
    ('Cold Horlick','凍可立克'),
    ('Cold Honey With Lemon','凍檸蜜'),
    ('Cold Honey With Watercress','凍菜蜜'),
    ('Soybean Milk','豆漿'),
    ('Coca Cola','可口可樂'),
    ('Coke Zero','無糖可樂'),
    ('Spirit','雪碧'),
    ('Fanta','芬達'),
    ('Ice Water','冰水'),
    ('Egg','煎蛋'),
    ('Ham','火'),
    ('Luncheon Meat','火腿'),
    ('Cheese Sausage','芝士腸'),
    ('Red Sausage','紅腸'),
    ('Satay Beef','沙嗲牛肉'),
    ('Spiced Pork Cubes','五香肉丁'),
    ('Chicken','雞扒'),
    ('Mini Macaroni With Ham','迷你火腿通粉'),
    ('Mini Macaroni With Spcied Pork Cubes','迷你五香肉丁通粉'),
    ('Mini Noodle With Spiced Pork Cubes','迷你火腿福麵'),
    ('Mini Noodle With Ham','迷你五香肉丁福麵'),
    ('Macaroni With Ham','火腿通粉'),
    ('Macaroni With Spcied Pork','五香肉丁通粉'),
    ('Noodle With Ham','火腿福麵'),
    ('Noodle With Spiced Pork','五香肉丁福麵'),
    ('Nissan Noodle With Ham','火腿出前一丁麵'),
    ('Nissan Noodle With Spiced Pork','五香肉丁出前一丁麵'),
    ('Toast','多士'),
    ('Bun','麵包'),
    ('Baked Bean','焗豆'),
    ('Macaroni','通粉'),
    ('Noodle','福麵'),
    ('Nissan Noodle','出前一丁麵'),
    ('Mixian','米線'),
    ('Beef','牛肉'),
    ('Pork Liver','豬潤'),
    ('Cheese','芝士');

    
    
    
    
    